DROP TABLE IF EXISTS lesson_groupe CASCADE;
DROP TABLE IF EXISTS lesson_student_mapping CASCADE;
DROP TABLE IF EXISTS teacher_course CASCADE;
DROP TABLE IF EXISTS teacher_lesson CASCADE;
DROP TABLE IF EXISTS course_groupe CASCADE;
DROP TABLE IF EXISTS user_role CASCADE;


DROP TABLE IF EXISTS lesson_student CASCADE;
DROP TABLE IF EXISTS enrollment CASCADE;
DROP TABLE IF EXISTS lesson CASCADE;

DROP TABLE IF EXISTS student CASCADE;
DROP TABLE IF EXISTS teacher CASCADE;
DROP TABLE IF EXISTS groupe CASCADE;
DROP TABLE IF EXISTS course CASCADE;
DROP TABLE IF EXISTS room CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS userr CASCADE;

DROP TABLE IF EXISTS department CASCADE;
DROP TABLE IF EXISTS faculty CASCADE;
DROP TABLE IF EXISTS university CASCADE;

